In [59]:
import pandas as pd

In [60]:
df_appstore = pd.read_csv("AppleStore.csv")

In [61]:
df_playstore = pd.read_csv("googleplaystore.csv")

In [62]:
display(df_appstore.head(100))

,Unnamed: 0,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,1,281656475,PAC-MAN Premium,100788224,USD,3.99,21292,26,4.0,4.5,6.3.5,4+,Games,38,5,10,1
1,2,281796108,Evernote - stay organized,158578688,USD,0.00,161065,26,4.0,3.5,8.2.2,4+,Productivity,37,5,23,1
2,3,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,USD,0.00,188583,2822,3.5,4.5,5.0.0,4+,Weather,37,5,3,1
3,4,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,USD,0.00,262241,649,4.0,4.5,5.10.0,12+,Shopping,37,5,9,1
4,5,282935706,Bible,92774400,USD,0.00,985920,5320,4.5,5.0,7.5.1,4+,Reference,37,5,45,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,108,306169895,Tozzle - Toddler's favorite puzzle,168192000,USD,2.99,2562,10,4.0,4.5,5.1,4+,Games,37,5,4,1
96,109,306257910,HomeBudget with Sync,17485824,USD,4.99,3042,6,3.5,4.0,3.3.0,4+,Finance,37,5,11,1
97,110,306375551,Wind Meter,5234688,USD,0.99,338,12,2.5,2.0,5.0,4+,Weather,43,0,1,1
98,111,306468004,Map My Run+ - GPS Running & Workout Tracker,237913088,USD,2.99,16434,3,4.5,4.5,17.5.5,4+,Health & Fitness,37,0,9,1
99,112,306561234,Map My Ride+ - GPS Cycling & Route Tracker,233513984,USD,2.99,10046,7,4.5,5.0,17.5.5,4+,Health & Fitness,37,0,9,1

In [63]:
display(df_playstore.head(100))

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,All of the parking lot - National Park applica...,AUTO_AND_VEHICLES,4.0,1754,14M,"500,000+",Free,0,Everyone,Auto & Vehicles,"June 2, 2018",2.3.4,4.0 and up
96,Inquiry Fines and Debits of Vehicles,AUTO_AND_VEHICLES,4.4,2680,2.2M,"500,000+",Free,0,Everyone,Auto & Vehicles,"March 20, 2018",1.03,4.0.3 and up
97,Gas Station,AUTO_AND_VEHICLES,4.0,1288,4.5M,"100,000+",Free,0,Everyone,Auto & Vehicles,"April 21, 2018",2.17,4.0 and up
98,Hush - Beauty for Everyone,BEAUTY,4.7,18900,17M,"500,000+",Free,0,Everyone,Beauty,"August 2, 2018",6.10.1,5.0 and up
99,"ipsy: Makeup, Beauty, and Tips",BEAUTY,4.9,49790,14M,"1,000,000+",Free,0,Everyone,Beauty,"November 9, 2017",2.3.0,4.1 and up

In [64]:
print(df_appstore.columns)

Index(['Unnamed: 0', 'id', 'track_name', 'size_bytes', 'currency', 'price',
       'rating_count_tot', 'rating_count_ver', 'user_rating',
       'user_rating_ver', 'ver', 'cont_rating', 'prime_genre',
       'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic'],
      dtype='object')

In [65]:
print(df_playstore.columns)

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [66]:
import numpy as np

In [67]:
df_playstore = df_playstore[df_playstore['Rating'] <= 5]


df_playstore ['Installs'] = pd.to_numeric(df_playstore['Installs'].astype(str).str.replace(r'[+,]', '', regex=True), errors='coerce')
df_playstore ['Price'] = pd.to_numeric(df_playstore['Price'].astype(str).str.replace(r'[$,]', '', regex=True), errors='coerce')
df_playstore ['Reviews'] = pd.to_numeric(df_playstore['Reviews'], errors='coerce')

In [68]:
def clean_size(val):
    val = str(val).replace(',','')
    if 'M' in val:
        return float(val.replace('M',''))
    elif 'k' in val:
        return float(val.replace('k',''))/1024
    return np.nan

In [69]:
df_playstore['Size_MB'] = df_playstore['Size'].apply(clean_size)

In [70]:
df_playstore_clean = pd.DataFrame({
    'App': df_playstore['App'],
    'Platform': 'Google Play Store',
    'Category': df_playstore['Category'],
    'Rating': df_playstore['Rating'],
    'Reviews': df_playstore['Reviews'],
    'Size_MB': df_playstore['Size_MB'],
    'Installs': df_playstore['Installs'],
    'Type': df_playstore['Type'],
    'Price': df_playstore['Price'],
    'Content Rating': df_playstore['Content Rating'],
    'Genres': df_playstore['Genres'],
    'Last Updated': pd.to_datetime(df_playstore['Last Updated'], errors='coerce'),
    'Current Ver': df_playstore['Current Ver'],
    'Android Ver': df_playstore['Android Ver']
})

In [71]:
df_appstore['size_bytes'] = df_appstore['size_bytes'] / 1024 / 1024

In [72]:
df_appstore_clean = pd.DataFrame({
    'App': df_appstore['track_name'],
    'Platform': 'Apple App Store',
    'Category': df_appstore['prime_genre'],
    'Rating': df_appstore['user_rating'],
    'Reviews': df_appstore['rating_count_tot'],
    'Size_MB': df_appstore['size_bytes'],
    'Price': df_appstore['price'],
}).dropna()

In [73]:
df_combined = pd.concat([df_playstore_clean, df_appstore_clean], ignore_index=True)

In [74]:
feature = df_combined[['Rating', 'Reviews', 'Price']]
for col in feature:
    df_combined[col] = pd.to_numeric(df_combined[col], errors='coerce')

In [75]:
df_combined = df_combined.dropna(subset=feature.columns).reset_index(drop=True)

In [76]:
X = df_combined[feature.columns].values

In [77]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [78]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)

In [79]:
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df_combined['Cluster_ID'] = kmeans.fit_predict(x_scaled)

In [80]:
df_combined.to_csv('combined_apps_with_clusters.csv', index=False)
print("Combined dataset with clusters saved to 'combined_apps_with_clusters.csv'")

Combined dataset with clusters saved to 'combined_apps_with_clusters.csv'

In [81]:
print(df_combined['Platform'].value_counts())

Platform
Google Play Store    9366
Apple App Store      7197
Name: count, dtype: int64

In [83]:
df = pd.read_csv('combined_apps_with_clusters.csv')
df_apple = df[df['Platform'] == 'Apple App Store']
display(df_apple.head(100))

,App,Platform,Category,Rating,Reviews,Size_MB,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Cluster_ID
9366,PAC-MAN Premium,Apple App Store,Games,4.0,21292,96.119141,NaN,NaN,3.99,NaN,NaN,NaN,NaN,NaN,0
9367,Evernote - stay organized,Apple App Store,Productivity,4.0,161065,151.232422,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0
9368,"WeatherBug - Local Weather, Radar, Maps, Alerts",Apple App Store,Weather,3.5,188583,95.867188,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0
9369,"eBay: Best App to Buy, Sell, Save! Online Shop...",Apple App Store,Shopping,4.0,262241,122.558594,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0
9370,Bible,Apple App Store,Reference,4.5,985920,88.476562,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9461,Tozzle - Toddler's favorite puzzle,Apple App Store,Games,4.0,2562,160.400391,NaN,NaN,2.99,NaN,NaN,NaN,NaN,NaN,0
9462,HomeBudget with Sync,Apple App Store,Finance,3.5,3042,16.675781,NaN,NaN,4.99,NaN,NaN,NaN,NaN,NaN,0
9463,Wind Meter,Apple App Store,Weather,2.5,338,4.992188,NaN,NaN,0.99,NaN,NaN,NaN,NaN,NaN,0
9464,Map My Run+ - GPS Running & Workout Tracker,Apple App Store,Health & Fitness,4.5,16434,226.891602,NaN,NaN,2.99,NaN,NaN,NaN,NaN,NaN,0
9465,Map My Ride+ - GPS Cycling & Route Tracker,Apple App Store,Health & Fitness,4.5,10046,222.696289,NaN,NaN,2.99,NaN,NaN,NaN,NaN,NaN,0